# Generated by Django 5.1.7 on 2025-03-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Auditeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['nom'], name='AppAudit_au_nom_f6f3a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.DurationField()),
                ('niveau', models.CharField(max_length=50)),
                ('itineraire', models.TextField()),
                ('date_prevu', models.DateField()),
                ('date_realisee', models.DateField(blank=True, null=True)),
                ('auditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='AppAudit.auditeur')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['numero_ligne'], name='AppAudit_li_numero__5372b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('unite', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='AppAudit.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('valeur_attendue', models.CharField(max_length=100)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='AppAudit.standard')),
            ],
        ),
        migrations.CreateModel(
            name='StandardAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_audits', to='AppAudit.audit')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_audits', to='AppAudit.standard')),
            ],
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['niveau'], name='AppAudit_au_niveau_27f843_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['date_prevu'], name='AppAudit_au_date_pr_4f5877_idx'),
        ),
    ]
