# Generated by Django 5.1.7 on 2025-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne',
            name='numero_ligne',
            field=models.CharField(max_length=10),
        ),
    ]
