# Generated by Django 5.1.7 on 2025-03-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0002_alter_ligne_numero_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='unite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
