# Generated by Django 5.1.7 on 2025-05-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0003_alter_standard_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ligne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='AppAudit.ligne'),
            preserve_default=False,
        ),
    ]
