# Generated by Django 5.1.7 on 2025-05-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0005_alter_audit_auditeur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditeur',
        ),
    ]
