# Generated by Django 5.1.7 on 2025-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0006_delete_auditeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardaudit',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='EN_COURS', max_length=50),
        ),
    ]
