# Generated by Django 5.1.7 on 2025-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0007_alter_standardaudit_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardaudit',
            name='statut',
        ),
        migrations.AddField(
            model_name='audit',
            name='resultat',
            field=models.CharField(blank=True, choices=[('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('NON_ATTRIBUE', 'Pas attribué')], default='NON_ATTRIBUE', max_length=20),
        ),
    ]
