# Generated by Django 5.1.7 on 2025-05-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0008_remove_standardaudit_statut_audit_resultat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='rep',
            field=models.TextField(blank=True, null=True),
        ),
    ]
