# Generated by Django 5.1.7 on 2025-06-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0010_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='photo_principale',
            field=models.ImageField(blank=True, null=True, upload_to='standards/photos/'),
        ),
    ]
