# Generated by Django 5.1.7 on 2025-06-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0011_standard_photo_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='AppAudit.standard'),
        ),
    ]
