# Generated by Django 5.1.7 on 2025-06-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0012_photo_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='photo_principale',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='standard',
        ),
    ]
