# Generated by Django 5.1.7 on 2025-06-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAudit', '0013_rename_photo_principale_standard_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards', to='AppAudit.photo'),
        ),
    ]
